# Dynamic configuration
http:
  routers:
    rport:
      entryPoints:
        - web
      rule: Host('rport.trevi.et')
      service: rport
    rport-secure:
      entryPoints:
        - websecure
      rule: Host('rport.trevi.et')
      service: rport

  services:
    rport-secure:
      loadbalancer:
        servers:
        - url: http://149.56.103.165:52443
        passHostHeader: true
    rport:
      loadbalancer:
        servers:
        - url: http://149.56.103.165:52080
        passHostHeader: true

  middlewares:
    secureHeaders:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    user-auth:
      basicAuth:
        users:
          - "admin:$apr1$eNLECaMO$1kIY.Lf3a8ttCyZ3EaDGx/"

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
